version: '3.5'
services:
  web:
    container_name: notion_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    tty: true
    networks:
      - react-notion

networks:
  react-notion:
    external: true
